insert into public.teams (code, name, aliases, confederation) values
('ALG', 'Argelia', '["Argelia", "Algeria"]'::jsonb, 'CAF'),
('ARG', 'Argentina', '["Argentina"]'::jsonb, 'CONMEBOL'),
('AUS', 'Australia', '["Australia"]'::jsonb, 'AFC'),
('AUT', 'Austria', '["Austria"]'::jsonb, 'UEFA'),
('BEL', 'Belgica', '["Belgica", "Bélgica", "Belgium"]'::jsonb, 'UEFA'),
('BIH', 'Bosnia', '["Bosnia", "Bosnia y Herzegovina", "Bosnia and Herzegovina"]'::jsonb, 'UEFA'),
('BOL', 'Bolivia', '["Bolivia"]'::jsonb, 'CONMEBOL'),
('BRA', 'Brasil', '["Brasil", "Brazil"]'::jsonb, 'CONMEBOL'),
('CAN', 'Canada', '["Canada", "Canadá"]'::jsonb, 'CONCACAF'),
('CHI', 'Chile', '["Chile"]'::jsonb, 'CONMEBOL'),
('CIV', 'Costa de Marfil', '["Costa de Marfil", "Ivory Coast", "Cote d''Ivoire", "Côte d''Ivoire"]'::jsonb, 'CAF'),
('CMR', 'Camerun', '["Camerun", "Camerún", "Cameroon"]'::jsonb, 'CAF'),
('COL', 'Colombia', '["Colombia"]'::jsonb, 'CONMEBOL'),
('CPV', 'Cabo Verde', '["Cabo Verde", "Cape Verde"]'::jsonb, 'CAF'),
('CRC', 'Costa Rica', '["Costa Rica"]'::jsonb, 'CONCACAF'),
('CRO', 'Croacia', '["Croacia", "Croatia"]'::jsonb, 'UEFA'),
('CUW', 'Curazao', '["Curazao", "Curaçao", "Curacao"]'::jsonb, 'CONCACAF'),
('DEN', 'Dinamarca', '["Dinamarca", "Denmark"]'::jsonb, 'UEFA'),
('ECU', 'Ecuador', '["Ecuador"]'::jsonb, 'CONMEBOL'),
('EGY', 'Egipto', '["Egipto", "Egypt"]'::jsonb, 'CAF'),
('ENG', 'Inglaterra', '["Inglaterra", "England"]'::jsonb, 'UEFA'),
('ESP', 'Espana', '["Espana", "España", "Spain"]'::jsonb, 'UEFA'),
('FRA', 'Francia', '["Francia", "France"]'::jsonb, 'UEFA'),
('GER', 'Alemania', '["Alemania", "Germany", "Deutschland"]'::jsonb, 'UEFA'),
('GHA', 'Ghana', '["Ghana"]'::jsonb, 'CAF'),
('GRE', 'Grecia', '["Grecia", "Greece"]'::jsonb, 'UEFA'),
('HAI', 'Haiti', '["Haiti", "Haití"]'::jsonb, 'CONCACAF'),
('HON', 'Honduras', '["Honduras"]'::jsonb, 'CONCACAF'),
('IRN', 'Iran', '["Iran", "Irán"]'::jsonb, 'AFC'),
('IRQ', 'Irak', '["Irak", "Iraq"]'::jsonb, 'AFC'),
('ISL', 'Islandia', '["Islandia", "Iceland"]'::jsonb, 'UEFA'),
('ITA', 'Italia', '["Italia", "Italy"]'::jsonb, 'UEFA'),
('JAM', 'Jamaica', '["Jamaica"]'::jsonb, 'CONCACAF'),
('JOR', 'Jordania', '["Jordania", "Jordan"]'::jsonb, 'AFC'),
('JPN', 'Japon', '["Japon", "Japón", "Japan"]'::jsonb, 'AFC'),
('KOR', 'Corea del Sur', '["Corea del Sur", "South Korea", "Korea Republic", "Corea"]'::jsonb, 'AFC'),
('KSA', 'Arabia Saudita', '["Arabia Saudita", "Arabia Saudi", "Arabia Saudí", "Saudi Arabia"]'::jsonb, 'AFC'),
('MAR', 'Marruecos', '["Marruecos", "Morocco"]'::jsonb, 'CAF'),
('MEX', 'Mexico', '["Mexico", "México"]'::jsonb, 'CONCACAF'),
('NED', 'Paises Bajos', '["Paises Bajos", "Países Bajos", "Holanda", "Netherlands", "Holland"]'::jsonb, 'UEFA'),
('NGA', 'Nigeria', '["Nigeria"]'::jsonb, 'CAF'),
('NOR', 'Noruega', '["Noruega", "Norway"]'::jsonb, 'UEFA'),
('NZL', 'Nueva Zelanda', '["Nueva Zelanda", "New Zealand"]'::jsonb, 'OFC'),
('PAN', 'Panama', '["Panama", "Panamá"]'::jsonb, 'CONCACAF'),
('PAR', 'Paraguay', '["Paraguay"]'::jsonb, 'CONMEBOL'),
('PER', 'Peru', '["Peru", "Perú"]'::jsonb, 'CONMEBOL'),
('POL', 'Polonia', '["Polonia", "Poland"]'::jsonb, 'UEFA'),
('POR', 'Portugal', '["Portugal"]'::jsonb, 'UEFA'),
('QAT', 'Catar', '["Catar", "Qatar"]'::jsonb, 'AFC'),
('RSA', 'Sudafrica', '["Sudafrica", "Sudáfrica", "South Africa"]'::jsonb, 'CAF'),
('RUS', 'Rusia', '["Rusia", "Russia"]'::jsonb, 'UEFA'),
('SCO', 'Escocia', '["Escocia", "Scotland"]'::jsonb, 'UEFA'),
('SEN', 'Senegal', '["Senegal"]'::jsonb, 'CAF'),
('SRB', 'Serbia', '["Serbia"]'::jsonb, 'UEFA'),
('SUI', 'Suiza', '["Suiza", "Switzerland"]'::jsonb, 'UEFA'),
('SWE', 'Suecia', '["Suecia", "Sweden"]'::jsonb, 'UEFA'),
('TUN', 'Tunez', '["Tunez", "Túnez", "Tunisia"]'::jsonb, 'CAF'),
('UKR', 'Ucrania', '["Ucrania", "Ukraine"]'::jsonb, 'UEFA'),
('URU', 'Uruguay', '["Uruguay"]'::jsonb, 'CONMEBOL'),
('USA', 'Estados Unidos', '["Estados Unidos", "USA", "United States", "EEUU", "EE.UU."]'::jsonb, 'CONCACAF'),
('UZB', 'Uzbekistan', '["Uzbekistan", "Uzbekistán"]'::jsonb, 'AFC'),
('VEN', 'Venezuela', '["Venezuela"]'::jsonb, 'CONMEBOL'),
('WAL', 'Gales', '["Gales", "Wales"]'::jsonb, 'UEFA')
on conflict (code) do update set name=excluded.name, aliases=excluded.aliases, confederation=excluded.confederation;